import Head from "next/head";
import Image from "next/image";

const experiences = [
  {
    company: "Free",
    logo: "/logo_free.png",
    role: "développeur full-stack - Product Owner technique",
  },
  {
    company: "Palo IT Singapour",
    logo: "/logo_palo_it.svg",
    role: "lead développeur full-stack",
  },
  {
    company: "SOAT",
    logo: "/logo-soat.webp",
    role: "développeur full-stack",
  },
  {
    company: "Sopra Steria",
    logo: "/logo-sopra.png",
    role: "développeur full-stack",
  },
];

export default function Home() {
  return (
    <div className="min-h-screen bg-darkGray text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Baptiste BORDET</h1>
      </header>

      <main className="container">
        {experiences.map(({ company, logo, role }) => (
          <div className="p-6">
            <div className="flex items-center">
              <Image src={logo} alt={company} width={100} height={50} />{" "}
              <h2 className="text-4xl ml-3">{company}</h2>
            </div>
            <span>{role}</span>
          </div>
        ))}
      </main>

      <footer>
        <span>lien linkedin</span>
        <span>lien insta</span>
      </footer>
    </div>
  );
}
