import Head from 'next/head'
import Image from 'next/image'

const experiences = [
    {
        company: 'Free',
        logo: '/logo_free.png',
        role: 'développeur full-stack - Product Owner technique'
    },
    {
        company: 'Palo IT Singapour',
        logo: '/logo_palo_it.svg',
        role: 'lead développeur full-stack'
    },
    {
        company: 'SOAT',
        logo: '/logo_free.png',
        role: 'développeur full-stack'
    },
    {
        company: 'Sopra Steria',
        logo: '/logo_free.png',
        role: 'développeur full-stack'
    },
]

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Baptiste BORDET</h1>

          {experiences.map(({ company, logo, role }) => (
              <div>
                  <Image src={logo} alt={company} width={200} height={100}/> <h2>{company}</h2>
                  <span>{role}</span>
              </div>
          ))}

      </main>

      <footer>
          <span>lien linkedin</span>
          <span>lien insta</span>
      </footer>
    </div>
  )
}
